version: "3"

services:
  client:
    build: greet/greet_client
    restart: always
    depends_on:
      - server
  server:
    build: greet/greet_server
    restart: always
    ports:
      - 50051:50051